### ISSUE TITLE
undefined symbol: onGameModeInit

### ISSUE THREAD

**Issue by alph4b3th** [goseventh/rakstar#2]
> # Introdução do problema
> Uau, eu realmente não sei o que está rolando, parece que funções Go não são exportadas para a lib C, mas por quê? O Problema estourou quando movi **./libs** e **./rakstar.go** para **./internal** - _Algo de errado não está certo_
> ### Por que mover para **internal**? 
> Não faz sentido. Códigos internos devem ficar em **internal**, por que **rakstar.go** seria excecão? 
> ### Já tentou reverter as alterações? (mover **libs**, **rakstar.go** para fora de **internal**)
> Não. Decidi abrir uma issue para relatar os acontecimentos, antes que o problema se agrave.
> Não sabemos se a falha ocorreu durante algum **processo de refatoração e criação de sistemas rakstar**, ou se ocorreu quando movemos para o **internal**

> **Estamos em investigação para encontrar a falha, postaremos se houver novidades.**

**Comment by Real-DavidWilson** [comment]
### **Descrição:**

O problema enfrentado está diretamente relacionado ao funcionamento do Go, o Go tende a descartar módulos em desuso na hora do build, e infelizmente, o módulo "**callbacks**" está sendo afetado por esse comportamento.

O módulo "**callbacks**" é crucial para o correto funcionamento do **rakstar**, pois nele contém as configurações do **CGO** para o uso de callbacks do "**sa-mp**".

Dessa forma, é imprescindível garantir que o módulo "**callbacks**" seja devidamente utilizado em alguma parte do projeto, evitando assim o descarte indevido e garantindo o correto funcionamento das configurações do **CGO** para o uso de callbacks do "**sa-mp**".

### **Soluções Propostas:**

A seguir, apresento duas soluções para resolver o problema relacionado ao descarte indevido do módulo "**callbacks**" durante o processo de build do Go, afetando o correto funcionamento do **rakstar**.

#### **Solução 1: Utilizar Função Vazia no Módulo "callbacks"**

Na primeira solução, recomendo criar uma função vazia no arquivo principal do módulo "**callbacks**". O código da função a ser adicionada é o seguinte:

```go
// callbacks.go
package callbacks

func Boot() {}
```

Após adicionar essa função, é **necessário invocá-la** em algum lugar do projeto para que o módulo **callbacks** seja corretamente utilizado durante o processo de build. No entanto, é importante ressaltar que essa solução é considerada uma medida temporária, uma "gambiarra", e deve ser reorganizada futuramente para uma solução mais robusta.

#### **Solução 2: Reorganizar os Módulos Diretamente Relacionados ao "sa-mp"**

A segunda solução propõe reorganizar os módulos que tratam diretamente do **sa-mp**. Uma abordagem viável é criar um novo módulo, por exemplo **samp**, que englobe esses submódulos em uma única unidade. Isso garantirá que o módulo **callbacks** seja utilizado e não seja descartado durante o processo de build.

Essa solução é mais recomendada a longo prazo, pois proporciona uma organização mais estruturada e sustentável do projeto **rakstar**.

As soluções apresentadas têm como objetivo resolver o problema e assegurar o correto funcionamento do **rakstar** em relação ao uso do módulo "**callbacks**" e às configurações do **CGO** para o uso de callbacks do **sa-mp**.

**Comment by alph4b3th** [comment]
> Uau, isso foi incrível! **Bom trabalho!** Sinceramente isso é um **problema tosco**, um pequeno detalhe que **faz toda a diferença**, se não fosse por isso eu confesso que estaria procurando em outros lugares na esperança de achar uma falha em algum trecho de código, haha!

> **Sobre as soluções** eu gostaria de introduzir uma **terceira solução que aproveita a primeira** e tenta organizar as coisas. Se trata de "mover" a função **On** presente no arquivo **rakstar.go** para dentro de **callbacks.go**. Dessa forma teríamos um motivo para importar **callbacks.go**, já que ao **inicializar módulos internos** como **server.Boot()**, os módulos filhos **"chat", "command" etc..** se **inscreveriam** em **callbackXXXXX** usando a função **On**: **On("calbackXXXXX")**

**Comment by Real-DavidWilson** [comment]
O problema foi completamente resolvido por meio de uma reestruturação completa do projeto, que incluiu a implementação da 3ª solução proposta. As mudanças realizadas estão nos commits abaixo:

Commits:
[:sparkles:  feat: server package](https://github.com/goseventh/rakstar/commit/af8debc4685a2a46ef8c9c185459a4bf02cd44f3)
[:rocket: refactor: reestruturação do projeto](https://github.com/goseventh/rakstar/commit/5954c43871efb9a893004f901154203b2d787480)
