### ISSUE TITLE
 Erro intermitente ao utilizar a função "Ignite" do módulo "vehicles"

### ISSUE THREAD

**Issue by Real-DavidWilson** [goseventh/rakstar#8]
:sparkles: **Descrição da falha**

Estava ocorrendo um 'panic' quando eu utilizava a função 'Ignite' do builder do módulo 'vehicles'. No entanto, pouco tempo depois, testei o código novamente e, aparentemente, o erro deixou de ocorrer.

:test_tube: **Como reproduzir:**
Passos para reproduzir o comportamento:
1. Inicialize o builder de "vehicles" com a função "Builder"
2. Chame a função "Ignite"
3. Crie o veículo com a função "Create"

:heavy_check_mark: **Comportamento esperado**

Pode ocorrer ou não uma mensagem como esta abaixo:

"[rakstar] a panic ocurred in the server manager" 

Após a exibição dessa mensagem, a execução do restante do código será interrompida.

:computer: **Desktop (por favor, complete as seguintes informações):**
- **SO:** Ubuntu 22.10 x86_64
- **Versão Go:** 1.20.6
- **Versão Rakstar** v0.0.1-alpha

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by alph4b3th** [comment]
![image](https://github.com/goseventh/rakstar/assets/66482679/7a78b922-fd49-448b-b7e0-64d46e0c20ec)

**Comment by alph4b3th** [comment]
@Real-DavidWilson poderia realizar os procedimentos acima, respectivamente?

**Comment by Real-DavidWilson** [comment]
Ao revisar os passos, percebi que havia comentado a linha 82 no arquivo "engine.go" dentro do módulo "vehicles" no framework. Foi uma falha minha e, como resultado, o erro deixou de ser intermitente.

**Comment by alph4b3th** [comment]
Realizei o passo acima e está comprovado:
![image](https://github.com/goseventh/rakstar/assets/66482679/03df889c-927f-4692-b8a3-c38af8b66682)

**Comment by alph4b3th** [comment]
# :bulb: Falha encontrada! - Por essa nós não esperávamos
Há uma falha categoria 1 no meio de diversos códigos mas minha hipótese estava correta: Natives.GetVehicleParamEx (**linha: 79**) recebe parâmetros do samp e exigia endereços de memória mas a função recebia nil conforme demonstrado abaixo

```go
	natives.GetVehicleParamsEx(
		e.v.id,
		nil, //uau, isso está definitivamente muito errado...
		&lights,
		nil, //uau, isso está definitivamente muito errado...
		nil, //uau, isso está definitivamente muito errado...
		nil, //uau, isso está definitivamente muito errado...
		nil, //uau, isso está definitivamente muito errado...
		nil, //uau, isso está definitivamente muito errado...
	)
```   

## :sparkles: Agora estamos investigando como resolver:
Não é tão simples. A native exige endereços de memória que **nunca serão utilizados pelo código**, isso é um grande desperdício de recursos! - Quem projetou essa porcaria? - Estamos neste momento, realizando inúmeros testes para **construir a melhor solução possível**. Esperamos que, conseguiremos usar uma abordagem mais eficiente do que alocações nulas, mas tenham em mente de que se trata de Samp e infelizmente Kalcor não é um bom programador, por tanto, temos que nos virar algumas vezes - E isso não é errado, pelo menos há outras coisas piores com o pawn que você talvez nem queira saber 

Se você leitor, quiser contribuir com uma solução criativa - mesmo se essa isssue esteja encerrada - por favor não nos hesite em postar em #3  seguindo o [código de conduta](https://github.com/goseventh/rakstar/blob/79fb85ae7363610bc7bd2dda982e6ffa4b85667d/CODE_OF_CONDUCT.md)

**Comment by alph4b3th** [comment]
## :bulb: Temporariamente, decidimos alocar:

Eu sei que esta não é a melhor abordagem e há desperdícios de recursos - mas é o melhor que temos para hoje, se você puder contribuir com outra abordagem leia a mensagem acima. 

Esta issue está sendo encerrada, mas você leitor ainda poderá contribui-la conforme descrito no post anterior. A solução está disponível em: 969d7bf6103dc750117c8835e96ab83b913d8378

Sinta-se a vontade para postar sua sugestão, mas lembre-se de seguir o [código de conduta](https://github.com/goseventh/rakstar/blob/79fb85ae7363610bc7bd2dda982e6ffa4b85667d/CODE_OF_CONDUCT.md),
**- Líder chefe do RakStar**
